[package]
name = "popcount_perf"
version = "0.1.0"
edition = "2018"
authors = ["Isaac Leonard <isaac@isaacleonard.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
